### PR TITLE
[WIP] NetUtil improvements

### PR DESCRIPTION
**Pull request by ghost**
Please not merge this until i finish. Only for feedback atm.

### CODE REVIEW

**Comment by ensirius** [comment]
@Steveice10 please give some feedback about last change.

**Comment by ghost** [comment]
I need some help @Steveice10. Look at 3719bc92b9ab509e4a8e93c9fd4426aaf335affd. I can't pass PacketBufferInput(Output) in packets. O_o

**Comment by ghost** [comment]
You can't just change the type like that. The interface expects to be able to pass any NetInput/Output in, and you don't even have a way of telling it to use your special NetInout/Output class.

I'm in favor of the current method for abstraction.

**Comment by ghost** [comment]
Well, if you not interested in other changes, gl :)

**Comment by ghost** [comment]
I'm fine with outside contributions, and if I don't like a change I usually give a reason why. I was fine with some of your changes, like the improvements to position reading and the addition of a NetUtil test, however they were lumped in with the NetInput/Output changes that I disagreed with. Separating changes by intent is probably the best way to get changes in. (e.g. improvements to NetUtil + related tests in their own PR, major changes to network I/O in another)

**Pull request closed without merging**
