### PR TITLE
MC 1.9.4 support

### PR DESCRIPTION
**Pull request by finalchild**
I think it complete, but it may lack something.

### CODE REVIEW

**Comment by Steveice10** [comment]
Has this been tested?

**Comment by ghost** [comment]
Since I don't have any testing methods, I couldn't.
I just tracked wiki.vg's protocol history.

**Comment by Steveice10** [comment]
Have you at least tried to log in to a server with it?

**Comment by kukelekuuk00** [comment]
The version number still says 1.9.2

**Comment by kukelekuuk00** [comment]
I get "Internal Network Exception" when trying to connect to a server (1.9.4 bungeecord) with this update.

**Comment by goosewoman** [comment]
https://gist.github.com/kukelekuuk00/ddf4b5108e69ca1f3953145adb1e291c

Is what I get on my chatclient trying to connect to a 1.9.4 bungeecord server. Unsure what kind of exception is actually thrown, because it gets caught before I can touch upon it.

Might I recommend an easier way of figuring out where the error lies? Like not catching the Exceptions before I can even begin to try to figure out if they're thrown. (iirc the exception is caught in PacketLib)

**Comment by ghost** [comment]
I'll try to test it today.

**Comment by ghost** [comment]
I found a bug. Fixing it.

**Comment by ghost** [comment]
Yup fixed
- Tested with my chat client.
  https://github.com/finalchild/MCChatClient

**Pull request merged**
