### PR TITLE
Minor pom enhancements

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by Steveice10** [comment]
Could you remove the update to snapshot versions of dependencies? I'll make sure to do a release of them with updated netty/GSON if that's what you need, and then I'll bump them up to the new release version later.

**Comment by sgdc3** [comment]
Sure ;)

**Comment by Steveice10** [comment]
That was part of what I was referring to, but could you also remove the changes of dependencies (OpenNBT, etc) to snapshot versions?

**Comment by sgdc3** [comment]
Ah ok, i need that asap, is the project ready for a release version?

**Comment by Steveice10** [comment]
Yeah, I can do a release of the other projects with the dependencies updated. I just don't like depending on snapshot versions in other projects, as, for example, an MCProtocolLib release may not coincide with an OpenNBT release, resulting in a release build that depends on a snapshot build.

**Comment by sgdc3** [comment]
Yeah, i just wanted to propagate the maven changes quickly xD

**Comment by sgdc3** [comment]
@Steveice10 Done

**Comment by Steveice10** [comment]
Thanks, I'll get some releases out soon.

**Pull request merged**
