### PR TITLE
Update GitHub Actions + Jenkins.

### PR DESCRIPTION
**Pull request by Kichura**
Same and last PR as [Geyser's #3351](https://github.com/GeyserMC/Geyser/pull/3351) - This follows the same pattern as the GeyserConnect PR i made, however instead of JDK 17 outright; it will be JDK 11 instead for now.

### CODE REVIEW

**Comment by NathanKassab** [comment]
Why would you switch it to java 11? As shown in the pom this project is made for java 8

**Comment by Kichura** [comment]
> Why would you switch it to java 11? As shown in the pom this project is made for java 8

I switched this to JDK 11 to see if it was a better option for compatibility reasons - if it manages to break anything in process then i can undo it.

**Comment by NathanKassab** [comment]
Well in that case I don't see the point in updating, there doesn't seem to be any compatibility issues so why potentially break projects relying on this by forcing users onto a different java version?

**Comment by Kichura** [comment]
"potentionally break projects" - It never was my goal to achieve nor purposely do since it would sound like JDK 11 never had any compatibility system(s) to begin with when it's the opposite by default,

I am however aware that JDK 16/17 will break things that use old code so this is one reason why i went for 11 instead so that it isn't too bleeding edge.

**Pull request closed without merging**
